version: '3.3'
services:
   db:
     platform: linux/x86_64
     image: mysql:5.7
     volumes:
       - ./mysql:/var/lib/mysql
       - ./mysql-dump:/docker-entrypoint-initdb.d
     environment:
       MYSQL_ROOT_PASSWORD: 'root'
       MYSQL_DATABASE: 'blab'
       MYSQL_USER: 'blab'
       MYSQL_PASSWORD: 'z2^E6J4$$;u;d'
     ports:
       - 3306:3306