version: '3.3'
services:
  web-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-Tomcat
    ports: 
      - "8080:8080"
    environment:
      CLASSPATH: /usr/local/tomcat/webapps/ROOT/WEB-INF/lib
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blab
      MYSQL_USER: blab
      MYSQL_PASSWORD: "z2^E6J4$$;u;d"